### ISSUE TITLE
能生成中文commit message吗?如果可以要怎么做呢

### ISSUE THREAD

**Issue by duzefu** [Undertone0809/gcop#118]
## Checklist

- [ ] I've searched the project's [`issues`](https://github.com/Undertone0809/gcop/issues?q=is%3Aissue).

## ❓ Question

How can I [...]?

Is it possible to [...]?

**Comment by Undertone0809** [comment]
- 优化了一下文档，你可以在 https://gcop.zeeland.top/guide/configuration.html#commit-message-template 查看如何自定义 commit message，我基于你的 issue 构建了一个示例，可以参考其他。
- 此外提供了 [how-to-guide](https://gcop.zeeland.top/guide/how-to-guide) 文档

可以参考 [upgrade](https://gcop.zeeland.top/guide/upgrade.html) 先更新到最新版本，再读上面的文章自定义 commit 模板。

**Comment by duzefu** [comment]
```
vscode@763f0e9ed184:/workspaces/rockchip/my1126$ git c
Traceback (most recent call last):
  File "/home/vscode/.local/bin/gcop", line 5, in <module>
    from gcop.__main__ import app
  File "/home/vscode/.local/lib/python3.8/site-packages/gcop/__main__.py", line 18, in <module>
    from gcop.config import ModelConfig, gcop_config
  File "/home/vscode/.local/lib/python3.8/site-packages/gcop/config.py", line 128, in <module>
    gcop_config = GcopConfig.from_yaml()
  File "/home/vscode/.local/lib/python3.8/site-packages/gcop/config.py", line 98, in from_yaml
    config: dict = read_yaml(config_path or cls._config_path)
  File "/home/vscode/.local/lib/python3.8/site-packages/gcop/utils/__init__.py", line 97, in read_yaml
    with open(file_path, "r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vscode/.zeeland/gcop/config.yaml'
```
我用`pip install gcop -U`更新到了最新的版本.似乎出了问题,
```
vscode@763f0e9ed184:/workspaces/rockchip/my1126$ gcop init
Traceback (most recent call last):
  File "/home/vscode/.local/bin/gcop", line 5, in <module>
    from gcop.__main__ import app
  File "/home/vscode/.local/lib/python3.8/site-packages/gcop/__main__.py", line 18, in <module>
    from gcop.config import ModelConfig, gcop_config
  File "/home/vscode/.local/lib/python3.8/site-packages/gcop/config.py", line 128, in <module>
    gcop_config = GcopConfig.from_yaml()
  File "/home/vscode/.local/lib/python3.8/site-packages/gcop/config.py", line 98, in from_yaml
    config: dict = read_yaml(config_path or cls._config_path)
  File "/home/vscode/.local/lib/python3.8/site-packages/gcop/utils/__init__.py", line 97, in read_yaml
    with open(file_path, "r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vscode/.zeeland/gcop/config.yaml'
```

**Comment by Undertone0809** [comment]
好，我来看看

**Comment by duzefu** [comment]
cp ~/.gcop/config.yaml  ~/.zeeland/gcop/
我执行这个之后正常了

**Comment by Undertone0809** [comment]
感谢反馈！

对的，直接 copy 就能使用，就是那个 自动化 migrate 出了点 bug，I will fix it.
